#pragma once
#include "Entity.h"

#define OBJECT_PHYSICAL_SIZE	14
#define OBJECT_FRAME_SIZE		16

#define POINTS_100	100
#define POINTS_200	200
#define POINTS_300	300
#define POINTS_350	350
#define POINTS_500	500
#define POINTS_550	550
#define POINTS_600	600
#define POINTS_650	650
#define POINTS_700	700

#define POINTS_1000	1000
#define POINTS_2000	2000
#define POINTS_3000	3000
#define POINTS_4000	4000


enum class ObjectType {
	ITEM_PINKCANDY, ITEM_BLUECANDY, ITEM_YELLOWCANDY, ITEM_JORDANS, ITEM_CLOCK, ITEM_BOMB, ITEM_ORANGEUMBRELLA, ITEM_REDUMBRELLA, ITEM_PINKUMBRELLA, ITEM_CHERRY, ITEM_BEER, ITEM_BANANA,
	ITEM_BORGER, ITEM_WATERMELON, ITEM_BLUERING, ITEM_PINKRING, ITEM_REDRING, ITEM_CROSS, ITEM_LIGHTNINGPOWER, ITEM_E, ITEM_X, ITEM_T, ITEM_E2, ITEM_N, ITEM_D, ITEM_THUNDERBOBBLE, ITEM_WATERBOBBLE, ITEM_FIREBOBBLE, ITEM_REDXBOBBLE
};

class Object : public Entity
{
public:
	Object(const Point& p, ObjectType t);
	~Object();

	void DrawDebug(const Color& col) const;
	int Points() const;

private:
	ObjectType type;
};

